//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impairement.Models.InstitutionModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class impairement
    {
        public int id_impairement { get; set; }
        public string amortization__type { get; set; }
        public Nullable<decimal> provision { get; set; }
        public Nullable<int> restructured { get; set; }
        public string risk_class { get; set; }
        public Nullable<decimal> osb_less_dcfs { get; set; }
        public Nullable<decimal> impairement_loss_year1 { get; set; }
        public Nullable<decimal> impairement_loss_year2 { get; set; }
        public Nullable<decimal> written_off_year2 { get; set; }
        public Nullable<decimal> recovered_in_year2 { get; set; }
        public Nullable<decimal> o_principle { get; set; }
        public Nullable<decimal> impairement1 { get; set; }
        public Nullable<decimal> is_it_still_impaired { get; set; }
        public Nullable<decimal> is_it_writen_off { get; set; }
        public Nullable<decimal> recovery_from_impairement { get; set; }
        public string product_id { get; set; }
        public int sector_id { get; set; }
        public string account_id { get; set; }
        public string customer_number { get; set; }
        public int branch_id { get; set; }
    
        public virtual account account { get; set; }
        public virtual branch branch { get; set; }
        public virtual customer customer { get; set; }
        public virtual product product { get; set; }
        public virtual sector sector { get; set; }
    }
}
