//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impairement.Models.InstitutionModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class loanline
    {
        public int id_loan_line { get; set; }
        public string application_id { get; set; }
        public Nullable<System.DateTime> date_of_disbursement { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> os_principle { get; set; }
        public Nullable<decimal> os_interest { get; set; }
        public Nullable<decimal> loan_balance { get; set; }
        public Nullable<int> terms { get; set; }
        public Nullable<decimal> arrears_amount { get; set; }
        public Nullable<decimal> interest_rate { get; set; }
        public Nullable<decimal> arrears_principle { get; set; }
        public Nullable<decimal> arrears_interest { get; set; }
        public Nullable<int> loan_series { get; set; }
        public Nullable<int> last_due { get; set; }
        public Nullable<int> business_sector { get; set; }
        public Nullable<int> sub_sector { get; set; }
        public Nullable<int> sub_sub_sector { get; set; }
        public Nullable<int> purpose { get; set; }
        public string repayment_account { get; set; }
        public Nullable<decimal> interest { get; set; }
        public Nullable<System.DateTime> installment_star__date { get; set; }
        public string credit_office__ID { get; set; }
        public string frequency { get; set; }
        public Nullable<int> calculation_method { get; set; }
        public Nullable<int> number_of_loans { get; set; }
        public Nullable<decimal> clearBalance { get; set; }
        public Nullable<decimal> provisionOSP { get; set; }
        public Nullable<decimal> provisionOSI { get; set; }
        public Nullable<decimal> provisionLOM { get; set; }
        public Nullable<decimal> provisionAsAT { get; set; }
        public Nullable<decimal> provisionATEOM { get; set; }
        public Nullable<int> daysLate_Number { get; set; }
        public Nullable<int> daysLateAv { get; set; }
        public Nullable<decimal> interestTOEOM { get; set; }
        public Nullable<decimal> gl_interest_month { get; set; }
        public Nullable<decimal> interestpaid { get; set; }
        public Nullable<decimal> principle_in_start_date { get; set; }
        public Nullable<decimal> due_days { get; set; }
        public Nullable<System.DateTime> last_installment_paid_date { get; set; }
        public Nullable<decimal> suspended_interest { get; set; }
        public Nullable<decimal> interest_receivable { get; set; }
        public Nullable<decimal> actual_interest_receivable { get; set; }
        public Nullable<decimal> out_standing_balance { get; set; }
        public Nullable<decimal> installments_paid { get; set; }
        public Nullable<int> loan_cycle { get; set; }
        public Nullable<decimal> recovered_amount { get; set; }
        public Nullable<decimal> savings { get; set; }
        public Nullable<decimal> unrecovered { get; set; }
        public string trade { get; set; }
    
        public virtual loanheader loanheader { get; set; }
    }
}
