//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impairement.Models.InstitutionModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class lossdefaultpersector
    {
        public int id_loss_default_per_sector { get; set; }
        public int sector_id { get; set; }
    
        public virtual sector sector { get; set; }
    }
}
