//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impairement.Models.InstitutionModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class macroeconomicfactor
    {
        public int id_macro_economic_factor { get; set; }
        public string factor { get; set; }
    }
}
