//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impairement.Models.InstitutionModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class purpose
    {
        public int id_purpose { get; set; }
        public string purpose_description { get; set; }
        public string application_id { get; set; }
    
        public virtual loanheader loanheader { get; set; }
    }
}
