//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impairement.Models.InstitutionModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class security
    {
        public int id_security { get; set; }
        public string description { get; set; }
        public string loan_application_id { get; set; }
        public Nullable<decimal> value_of_security { get; set; }
        public Nullable<decimal> market_value { get; set; }
        public Nullable<decimal> forced_sale_value { get; set; }
        public Nullable<decimal> adjusted_sales_value { get; set; }
        public Nullable<decimal> discounted_cash_flows { get; set; }
    
        public virtual loanheader loanheader { get; set; }
    }
}
