//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impairement.Models.InstitutionModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class subsubsector
    {
        public int id_sub_sub_sector { get; set; }
        public string sub_sub_sector_description { get; set; }
        public int subSector_id { get; set; }
    
        public virtual subsector subsector { get; set; }
    }
}
